#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-late
#
# Run source vmctl-init-conf <confdir>

usage() {
	echo "Usage: source $0 <confdir>"
}

if [ -z "$1" ]; then
	usage
	return 2
fi

if [ "$1" = '--help' ] || [ "$1" = '-h' ]; then
	usage
	return 2
fi

CONFDIR="$1"
if [ -n "${BASH_SOURCE[0]}" ]; then
	VMCTLDIR=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
else
	VMCTLDIR=$(dirname "$(realpath "$0")")
fi
EXAMPLESDIR=$VMCTLDIR/examples/vm

# Create CONFDIR if necessary
if [ ! -d "$CONFDIR" ]; then
	mkdir --parent "$CONFDIR"
	if [ $? -ne 0 ]; then
		return 1
	fi
	cp --recursive --verbose "$EXAMPLESDIR"/* "$CONFDIR"
	if [ $? -ne 0 ]; then
		return 1
	fi
fi

# Ensure vmctl is available
if ! command -v vmctl &> /dev/null; then
	# Add the parent directory of this script to PATH
	export PATH="$VMCTLDIR:$PATH"
	if ! command -v vmctl &> /dev/null; then
		echo "Error: vmctl tool is still not found after adding $VMCTLDIR to PATH."
		return 1
	fi
fi

cd $CONFDIR
vmctl --help
