#!/usr/bin/env bash

CLOUDINIT_STAGE_DIR="$(mktemp -d)"
GUEST_BOOT_BASE="${CLOUDINIT_STAGE_DIR}/base.qcow2"
trap 'rm -rfv ${CLOUDINIT_STAGE_DIR}' EXIT

source "x86_64-q35-base.conf"

_pre() {
  _require_program mkisofs
  _require_program wget
  _require_vars "GUEST_BOOT"

  local meta_data_file="${CLOUDINIT_STAGE_DIR}/meta-data"
  local usr_data_file="${CLOUDINIT_STAGE_DIR}/user-data"

  if [[ -f "img/base.qcow2" ]]; then
    _fatal 1 "img/base.qcow2 exist; rename to avoid overwriting"
  fi

  cloudinit_get_img --ubuntu-25 \
    --cloud-img-path "${GUEST_BOOT}" \
    --resize-to 8G

  cloudinit_make_seed_img \
    --seed-img-path "${CLOUDINIT_STAGE_DIR}/seed.img" \
    --meta-data-file "${meta_data_file}" \
    --usr-data-file "${usr_data_file}" \
    --usr-name "vmuser" \
    --usr-passwd "vmuser"
}

_setup_cloudinit() {
  _setup_x86_64_q35_base

  QEMU_PARAMS+=("-drive" "id=cloud-init-seed,file=${CLOUDINIT_STAGE_DIR}/seed.img,format=raw,media=cdrom")
}

_post() {
  mkdir -p "img"
  mv "${GUEST_BOOT}" "img/base.qcow2"
}
