#!/usr/bin/env bash

CLOUDINIT_STAGE_DIR="$(mktemp -d)"
trap 'rm -rfv ${CLOUDINIT_STAGE_DIR}' EXIT

#CLOUDINIT_SSHKEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFAKEKEYPLACEHOLDER vmuser@placeholder"
GUEST_BOOT_BASE="${CLOUDINIT_STAGE_DIR}/base.qcow2"
source "x86_64-q35-base.conf"

cloudinit_wget_ubuntu() {
  local cloud_img_path="$1"
  local uimg="https://cloud-images.ubuntu.com/releases/plucky/release"
  uimg="${uimg}/ubuntu-25.04-server-cloudimg-amd64.img"
  wget -O "${cloud_img_path}" "${uimg}"
}

cloudinit_resize_img() {
  local cloud_img_path="$1"
  qemu-img resize "${cloud_img_path}" 8G
}

_pre() {
  _require_program mkisofs
  _require_program wget
  _require_vars "GUEST_BOOT"

  if [[ -f "img/base.qcow2" ]]; then
    _fatal 1 "img/base.qcow2 exist; rename to avoid overwriting"
  fi

  cloudinit_wget_ubuntu "${GUEST_BOOT}"
  cloudinit_resize_img "${GUEST_BOOT}"

  qemu-img resize "${GUEST_BOOT}" 8G

  local meta_data_file="${CLOUDINIT_STAGE_DIR}/meta-data"
  local usr_data_file="${CLOUDINIT_STAGE_DIR}/user-data"

  cloudinit_make_seed_img \
    --seed-img-path "${CLOUDINIT_STAGE_DIR}/seed.img" \
    --meta-data-file "${meta_data_file}" \
    --usr-data-file "${usr_data_file}" \
    --usr-name "vmuser" \
    --usr-passwd "vmuser"
}

_setup_cloudinit() {
  _setup_x86_64_q35_base

  QEMU_PARAMS+=("-drive" "id=cloud-init-seed,file=${CLOUDINIT_STAGE_DIR}/seed.img,format=raw,media=cdrom")
}

_post() {
  mkdir -p "img"
  mv "${GUEST_BOOT}" "img/base.qcow2"
}
