#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2020 Samsung Electronics Co., Ltd. All Rights Reserved.
#
# Written by Klaus Jensen <its@irrelevant.dk>

USAGE="usage: ${BASENAME} -c CONFIG kill

The \`kill\` command shuts down the running virtual machine defined by the
given \`CONFIG\` using a \`quit\` QEMU monitor command."

source "${BASEDIR}/common/msgs"
_run_sys_kill() {
  local curr_pid=""
  if [[ ! -f "${VMRUN}/pidfile" ]]; then
    return 1
  fi
  curr_pid="$(cat "${VMRUN}/pidfile")"
  if kill -0 "${curr_pid}" 2> /dev/null; then
    kill -9 "${curr_pid}"
  fi
  rm -f "${VMRUN}/pidfile"
  return 0
}

_kill() {
  _require_program socat

  local short="h"
  local long="help"

  if ! tmp=$(getopt -o "$short" --long "$long" -n "$BASENAME" -- "$@"); then
    exit 1
  fi

  eval set -- "$tmp"
  unset tmp

  while true; do
    case "$1" in
      '-h' | '--help' )
        _usage "$USAGE" 0
        ;;
      '--' )
        shift; break
        ;;
      '*' )
        _usage "$USAGE" 1
        ;;
    esac
  done

  _load_vm

  if ! _is_running; then
    _fatal 1 "$VMNAME does not appear to be running"
  fi

  if [[ -S "${VMRUN}/monitor" ]]; then
    local args=( "-" "UNIX-CONNECT:${VMRUN}/monitor")
    if echo quit | socat "${args[@]}" >> "${VMLOG}/full" 2>&1; then
      return 0
    fi
  fi

  if ! _run_sys_kill >> "${VMLOG}/full" ; then
      _fatal 1 "could not power off vm; see ${VMLOG}/full"
  fi

}
