#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2020 Samsung Electronics Co., Ltd. All Rights Reserved.
#
# Written by Klaus Jensen <its@irrelevant.dk>

USAGE="usage: ${BASENAME} -c CONFIG log [OPTION...]

The \`log\` command is used to view logs from the virtual machine defined by
the given \`CONFIG\`.

Options:
  -h, --help            display this help message and exit
  -f, --follow          output appended data as log grows"

_log() {
  local short="f,h"
  local long="follow,help"

  if ! tmp=$(getopt -o "$short" --long "$long" -n "$BASENAME" -- "$@"); then
    exit 1
  fi

  eval set -- "$tmp"
  unset tmp

  while true; do
    case "$1" in
      '-f' | '--follow' )
        local do_follow=1; shift
        ;;
      '-h' | '--help' )
        _usage "$USAGE" 0
        ;;
      '--' )
        shift; break
        ;;
      '*' )
        _usage "$USAGE" 1
        ;;
    esac
  done

  _load_vm

  if [[ -v do_follow ]]; then
    tail -f "${VMLOG}/qemu.log"
  else
    $PAGER "${VMLOG}/qemu.log"
  fi
}
