#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2025 Samsung Electronics Co., Ltd. All Rights Reserved.
#
# Written by Joel Granados <joel.granados@kernel.org>

source "${BASEDIR}/common/shellcheck"

MSG_CHECK_DAEMONIZED="The vm is most likely running interactively. \
Try to attach monitor using 'Ctrl-a c' and type THE COMMAND. \
Or add '-d' to vmctl command to run daemonized"


