#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2025 Samsung Electronics Co., Ltd. All Rights Reserved.
#
# Written by Joel Granados <joel.granados@kernel.org>


_qemu_kern_noimg_add() {
  _fatal 1 "${FUNCNAME[0]} is not supported yet"
}

_qemu_kern_img_add() {
  local cmdline_extra="$1"
  if [[ ! -v GUEST_KERNEL_BOOTDEV ]]; then
    GUEST_KERNEL_BOOTDEV="/dev/vda1"
  fi

  local cmdline="root=${GUEST_KERNEL_BOOTDEV} console=${GUEST_KERNEL_CONSOLE} ${cmdline_extra}"
  if [[ -v GUEST_KERNEL_APPEND_EXTRA ]]; then
    cmdline="$cmdline ${GUEST_KERNEL_APPEND_EXTRA}"
  fi

  QEMU_PARAMS+=("-kernel" "${kernel_dir}/${GUEST_KERNEL_IMAGE}")
  QEMU_PARAMS+=("-append" "$cmdline")
}

qemu_kern_add_custom() {
  local cmdline_extra=""
  local mod_share="9p"
  local long="kernel-dir:,cmdline-extra:,mod-share:"

  if ! tmp=$(getopt -o "" --long "$long" -n "${FUNCNAME[0]}" -- "$@"); then
    exit 1
  fi

  eval set -- "$tmp"
  unset tmp

  while true; do
    case "$1" in
      '--kernel-dir' )
        local kernel_dir="$2"; shift 2
        ;;
      '--cmdline-extra' )
        cmdline_extra="${cmdline_extra} $2"; shift 2
        ;;
      'mod-share' )
        mod_share="$2"; shift 2
        ;;
      '--' )
        shift; break
        ;;
      * )
        _fatal 1 "unknown argument '$1'"
        ;;
    esac
  done

  if [[ ! -v kernel_dir ]]; then
    _fatal 1 "${FUNCNAME[0]} Missing required --kernel-dir argument"
  fi

  for var in GUEST_KERNEL_IMAGE GUEST_KERNEL_CONSOLE; do
    if [[ ! -v ${var} ]]; then
      _fatal 1 "${FUNCNAME[0]} Missing var ${var}. Add it to ${VMCONFIG}"
    fi
  done

  if [[ -v NIX_STORE_PATH ]]; then
    _qemu_kern_noimg_add
  else
    _qemu_kern_img_add "${cmdline_extra}"
  fi

  local kernel_tag="kernel_dir"
  if [[ ${mod_share} == "9p" ]]; then
    QEMU_PARAMS+=("-virtfs" "local,path=${kernel_dir},security_model=none,readonly=on,mount_tag=${kernel_tag}")
  elif [[ ${mod_share} == "viofs" ]]; then
    qemu_virtiofsd_add_shared --shared-dir "${kernel_dir}" --tag "${kernel_tag}"
  else
    _fatal 1 "${FUNCNAME[0]}: Unknown kernel directory share type (${mod_share})"
  fi
}

