#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2025 Samsung Electronics Co., Ltd. All Rights Reserved.
#
# Written by Joel Granados <joel.granados@kernel.org>

_qemu_kern_img_add() {
  for var in GUEST_BOOT GUEST_BOOT_BASE; do
    if [[ ! -v ${var} ]]; then
      _fatal 1 "${FUNCNAME[0]} Missing var ${var}. Add it to ${VMCONFIG}"
    fi
  done

  if [[ ! -f "${VMROOT}/$GUEST_BOOT" ]]; then
    if [[ ! -f "${VMROOT}/$GUEST_BOOT_BASE" ]]; then
      _fatal 1 "base image '${VMROOT}/${GUEST_BOOT_BASE}' does not exist"
    fi

    _log "creating boot image ('$GUEST_BOOT') from base ('$GUEST_BOOT_BASE')"
    _log_named "qemu-img create" "$QEMU_IMG" create -f qcow2 -b "$(basename "$GUEST_BOOT_BASE")" \
      -F qcow2 "${VMIMG}/$(basename "$GUEST_BOOT")" "$GUEST_BOOT_SIZE"
  fi

  if [[ ! -v GUEST_KERNEL_BOOTDEV ]]; then
    GUEST_KERNEL_BOOTDEV="/dev/vda1"
  fi

  QEMU_PARAMS+=("-kernel" "${GUEST_KERNEL_CUSTOM_DIR}/${GUEST_KERNEL_IMAGE}")
  QEMU_PARAMS+=("-append" \
    "root=${GUEST_KERNEL_BOOTDEV} console=${GUEST_KERNEL_CONSOLE} ${GUEST_KERNEL_APPEND_EXTRA}")
}

_qemu_check_kern_globs() {
  for var in GUEST_KERNEL_IMAGE GUEST_KERNEL_CONSOLE; do
    if [[ ! -v ${var} ]]; then
      _fatal 1 "${FUNCNAME[0]} Missing var ${var}. Add it to ${VMCONFIG}"
    fi
  done
}

qemu_kernel_setup() {
  if [[ ! -v GUEST_KERNEL_CUSTOM_DIR ]]; then
    # Yes!; Do nothing with image-backed
    if [[ -v NIX_STORE_PATH ]]; then
      _qemu_check_kern_globs
      qemu_nix_add_noimgnix
    fi
    return
  fi

  _qemu_check_kern_globs

  if [[ -v NIX_STORE_PATH ]]; then
    qemu_nix_add_noimgnix
    local mod_share="virtiofs"
  else
    _qemu_kern_img_add
    local mod_share="9p"
  fi

  qemu_share_add --shared-dir "${GUEST_KERNEL_CUSTOM_DIR}" \
    --tag "kernel_dir" \
    --share-type "${mod_share}"
}
