#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2025 Samsung Electronics Co., Ltd. All Rights Reserved.
#
# Written by Joel Granados <joel.granados@kernel.org>

cloudinit_get_sshkey() {
  local long="key-file:"

  if ! tmp=$(getopt -o "" --long "$long" -n "${FUNCNAME[0]}" -- "$@"); then
    exit 1
  fi

  eval set -- "$tmp"
  unset tmp

  while true; do
    case "$1" in
      '--key-file' )
        local key_file="$2"; shift 2
        ;;
      '--' )
        shift; break
        ;;
      * )
        _fatal 1 "unknown argument '$1'"
        ;;
    esac
  done

  if [[ -v CLOUDINIT_SSHKEY && -n "${CLOUDINIT_SSHKEY}" ]]; then
    return
  fi

  if [[ ! -v key_file ]]; then
    local key_file=""
    key_file="$(find ~/.ssh -maxdepth 1 -type f -name "*.pub" | head -n 1)"
    if [[ -z "${key_file}" ]]; then
        _fatal 1 "No public key found in ~/.ssh. Try setting CLOUDINIT_SSHKEY."
    fi
  fi

  if [[ ! -f "${key_file}" ]]; then
    _fatal 1 "File not found ${key_file}"
  fi

  CLOUDINIT_SSHKEY=$(cat "${key_file}")
}

